export enum TransferStatus {
  CREATED = 'CREATED',
  VALIDATED = 'VALIDATED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  QUEUED = 'QUEUED',
  SUBMITTED = 'SUBMITTED',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  PENDING_SETTLEMENT = 'PENDING_SETTLEMENT',
  SETTLED = 'SETTLED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  REVERSED = 'REVERSED',
  EXPIRED = 'EXPIRED',
}

export const TERMINAL_TRANSFER_STATUSES = new Set<TransferStatus>([
  TransferStatus.COMPLETED,
  TransferStatus.FAILED,
  TransferStatus.CANCELLED,
  TransferStatus.RETURNED,
  TransferStatus.REVERSED,
  TransferStatus.EXPIRED,
]);