export enum PostingType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
  ACH = 'ACH',
  WIRE = 'WIRE',
  SWIFT = 'SWIFT',
  CARD_AUTHORIZATION = 'CARD_AUTHORIZATION',
  CARD_CAPTURE = 'CARD_CAPTURE',
  CARD_REFUND = 'CARD_REFUND',
  CRYPTO_DEPOSIT = 'CRYPTO_DEPOSIT',
  CRYPTO_WITHDRAWAL = 'CRYPTO_WITHDRAWAL',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT = 'LOAN_REPAYMENT',
  INVESTMENT_PURCHASE = 'INVESTMENT_PURCHASE',
  INVESTMENT_SALE = 'INVESTMENT_SALE',
  INTEREST = 'INTEREST',
  FEE = 'FEE',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum EntrySide {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum PostingStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  FAILED = 'FAILED',
}

export enum HoldStatus {
  ACTIVE = 'ACTIVE',
  RELEASED = 'RELEASED',
  PARTIALLY_RELEASED = 'PARTIALLY_RELEASED',
  EXPIRED = 'EXPIRED',
  CAPTURED = 'CAPTURED',
}

export enum ReversalType {
  FULL = 'FULL',
  PARTIAL = 'PARTIAL',
}

export enum ReversalReasonCode {
  CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
  ERROR_CORRECTION = 'ERROR_CORRECTION',
  FRAUD = 'FRAUD',
  CHARGEBACK = 'CHARGEBACK',
  REGULATORY = 'REGULATORY',
  DUPLICATE = 'DUPLICATE',
  OTHER = 'OTHER',
}

export enum BalanceType {
  LEDGER = 'LEDGER',
  CURRENT = 'CURRENT',
  AVAILABLE = 'AVAILABLE',
  PENDING = 'PENDING',
  HELD = 'HELD',
  RESERVED = 'RESERVED',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ReconciliationType {
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
  MANUAL = 'MANUAL',
}

export enum ReconciliationStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  BALANCED = 'BALANCED',
  VARIANCE_DETECTED = 'VARIANCE_DETECTED',
  RESOLVED = 'RESOLVED',
}

export enum JournalStatus {
  DRAFT = 'DRAFT',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  CANCELLED = 'CANCELLED',
}

export enum PostingBatchStatus {
  PENDING = 'PENDING',
  COMMITTED = 'COMMITTED',
  ROLLED_BACK = 'ROLLED_BACK',
}
