import type { CustomerDashboardData } from './types';

export const customerDashboardData: CustomerDashboardData = {
  profile: {
    id: 'cust_100142',
    firstName: 'Jordan',
    lastName: 'Parker',
    fullName: 'Jordan Parker',
    email: 'jordan.parker@atlasbank.com',
    lastLoginAt: '2026-07-08T21:14:00-05:00',
    segment: 'Premier Banking',
  },
  financialOverview: [
    { label: 'Available Balance', value: 24682.54, deltaLabel: '+2.4% vs yesterday', trend: 'up' },
    {
      label: 'Current Balance',
      value: 25391.18,
      deltaLabel: '+$4,850 payroll settled',
      trend: 'up',
    },
    {
      label: 'Checking',
      value: 18142.27,
      deltaLabel: 'ACH and card activity today',
      trend: 'neutral',
    },
    { label: 'Savings', value: 62048.91, deltaLabel: '+$500 weekly transfer', trend: 'up' },
    {
      label: 'Crypto',
      value: 14212.65,
      deltaLabel: 'BTC and ETH holdings',
      trend: 'up',
      tone: 'crypto',
    },
    {
      label: 'Net Worth',
      value: 164908.37,
      deltaLabel: '+3.1% month to date',
      trend: 'up',
      tone: 'investment',
    },
  ],
  accounts: [
    {
      id: 'acct_checking_1842',
      name: 'Atlas Checking',
      type: 'checking',
      accountMask: '...1842',
      routingNumber: '111000025',
      achNumber: '021000021',
      wireNumber: '026009593',
      swiftCode: 'CHASUS33',
      availableBalance: 18142.27,
      currentBalance: 18850.91,
    },
    {
      id: 'acct_savings_7751',
      name: 'Premier Savings',
      type: 'savings',
      accountMask: '...7751',
      routingNumber: '121000248',
      achNumber: '121000358',
      wireNumber: '122105155',
      swiftCode: 'WFBIUS6S',
      availableBalance: 62048.91,
      currentBalance: 62048.91,
    },
    {
      id: 'acct_crypto_3019',
      name: 'Atlas Crypto Wallet',
      type: 'crypto',
      accountMask: '...3019',
      routingNumber: 'N/A',
      achNumber: 'N/A',
      wireNumber: 'N/A',
      availableBalance: 14212.65,
      currentBalance: 14212.65,
    },
  ],
  quickActions: [
    { id: 'transfer', label: 'Transfer', description: 'Move funds between Atlas accounts' },
    { id: 'deposit', label: 'Deposit', description: 'Start ACH, wire, or check deposit' },
    { id: 'withdraw', label: 'Withdraw', description: 'Send funds to an external destination' },
    {
      id: 'statements',
      label: 'View Statements',
      description: 'Download monthly account statements',
    },
    { id: 'cards', label: 'Cards', description: 'Manage card controls and spending' },
    { id: 'crypto', label: 'Crypto', description: 'Review wallet transfers and custody' },
  ],
  transactions: [
    {
      id: 'txn_1',
      bookedAt: '2026-07-08T08:15:00-05:00',
      description: 'Payroll Deposit - Northwind Health Systems',
      category: 'Income',
      amount: 4850.32,
      status: 'Posted',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_2',
      bookedAt: '2026-07-08T12:44:00-05:00',
      description: 'Card Purchase - Whole Foods Market #10215 Austin TX',
      category: 'Groceries',
      amount: -126.44,
      status: 'Posted',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_3',
      bookedAt: '2026-07-07T09:10:00-05:00',
      description: 'Outgoing ACH - Lone Star Property Management',
      category: 'Housing',
      amount: -2100,
      status: 'Processing',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_4',
      bookedAt: '2026-07-07T14:02:00-05:00',
      description: 'Incoming Wire - Horizon Ventures LLC',
      category: 'Wire',
      amount: 12000,
      status: 'Completed',
      account: 'Premier Savings',
    },
    {
      id: 'txn_5',
      bookedAt: '2026-07-06T16:35:00-05:00',
      description: 'Wire Transfer - Acme Custody LLC BTC Purchase',
      category: 'Investments',
      amount: -7500,
      status: 'Completed',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_6',
      bookedAt: '2026-07-06T11:18:00-05:00',
      description: 'Card Purchase - Delta Air Lines ATL',
      category: 'Travel',
      amount: -642.88,
      status: 'Posted',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_7',
      bookedAt: '2026-07-05T07:42:00-05:00',
      description: 'Crypto Deposit - USDC via Ethereum',
      category: 'Crypto',
      amount: 2500,
      status: 'Completed',
      account: 'Atlas Crypto Wallet',
    },
    {
      id: 'txn_8',
      bookedAt: '2026-07-05T13:11:00-05:00',
      description: 'ATM Withdrawal - Chase ATM 08721 Dallas TX',
      category: 'Cash',
      amount: -200,
      status: 'Posted',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_9',
      bookedAt: '2026-07-04T10:03:00-05:00',
      description: 'Internal Transfer - Weekly Savings Sweep',
      category: 'Savings',
      amount: -500,
      status: 'Posted',
      account: 'Atlas Checking',
    },
    {
      id: 'txn_10',
      bookedAt: '2026-07-04T10:04:00-05:00',
      description: 'Internal Transfer - Weekly Savings Sweep',
      category: 'Savings',
      amount: 500,
      status: 'Posted',
      account: 'Premier Savings',
    },
  ],
  cryptoActivities: [
    {
      id: 'crypto_1',
      asset: 'BTC',
      network: 'Bitcoin',
      amount: 0.08124,
      amountLabel: '0.08124 BTC',
      status: 'Settled',
      time: '2026-07-08T17:25:00-05:00',
    },
    {
      id: 'crypto_2',
      asset: 'ETH',
      network: 'Ethereum',
      amount: 1.42,
      amountLabel: '1.42 ETH',
      status: 'Completed',
      time: '2026-07-07T15:54:00-05:00',
    },
    {
      id: 'crypto_3',
      asset: 'USDC',
      network: 'Ethereum',
      amount: 2500,
      amountLabel: '2,500.00 USDC',
      status: 'Pending',
      time: '2026-07-05T07:42:00-05:00',
    },
  ],
  cards: [
    {
      id: 'card_phys_1',
      label: 'Physical Card',
      cardholder: 'Jordan Parker',
      maskedNumber: 'Visa Infinite ...4821',
      status: 'Active',
      availableCredit: 18420,
      creditLimit: 25000,
      isFrozen: false,
    },
    {
      id: 'card_virtual_1',
      label: 'Virtual Card',
      cardholder: 'Jordan Parker',
      maskedNumber: 'Virtual Visa ...9014',
      status: 'Provisioning',
      availableCredit: 5000,
      creditLimit: 5000,
      isFrozen: true,
    },
  ],
  investment: {
    portfolioValue: 58255.73,
    dailyChange: 642.18,
    totalReturn: 8142.67,
    allocationProgress: 68,
    topHolding: 'BTC Spot Allocation',
  },
  loan: {
    productName: 'Atlas Home Equity Line',
    outstandingBalance: 28440.15,
    nextPaymentAmount: 625.44,
    nextPaymentDate: '2026-07-19T00:00:00-05:00',
    status: 'Current',
  },
  notifications: [
    {
      id: 'note_1',
      title: 'ACH transfer is processing',
      detail: 'Your $2,100 rent transfer will settle by 5:00 PM CT today.',
      createdAt: '2026-07-08T09:24:00-05:00',
      unread: true,
    },
    {
      id: 'note_2',
      title: 'Payroll deposit posted',
      detail: 'Northwind Health Systems payroll cleared into Atlas Checking.',
      createdAt: '2026-07-08T08:16:00-05:00',
      unread: true,
    },
    {
      id: 'note_3',
      title: 'Virtual card frozen',
      detail: 'Your virtual card remains frozen until the next online purchase.',
      createdAt: '2026-07-07T18:05:00-05:00',
      unread: false,
    },
    {
      id: 'note_4',
      title: 'USDC custody deposit pending finality',
      detail: 'The USDC transfer has 8 of 12 confirmations on Ethereum.',
      createdAt: '2026-07-05T07:49:00-05:00',
      unread: false,
    },
  ],
};
