export enum CardType {
  PHYSICAL_DEBIT = 'PHYSICAL_DEBIT',
  VIRTUAL_DEBIT = 'VIRTUAL_DEBIT',
  BUSINESS_DEBIT = 'BUSINESS_DEBIT',
  SINGLE_USE_VIRTUAL = 'SINGLE_USE_VIRTUAL',
  MERCHANT_LOCKED_VIRTUAL = 'MERCHANT_LOCKED_VIRTUAL',
}

export enum CardStatus {
  REQUESTED = 'REQUESTED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ISSUED = 'ISSUED',
  ACTIVATED = 'ACTIVATED',
  FROZEN = 'FROZEN',
  LOCKED = 'LOCKED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  REISSUED = 'REISSUED',
}

export const TERMINAL_CARD_STATUSES = new Set<CardStatus>([
  CardStatus.EXPIRED,
  CardStatus.CANCELLED,
  CardStatus.REISSUED,
]);

export enum CardNetwork {
  VISA = 'VISA',
  MASTERCARD = 'MASTERCARD',
}

export enum CardSpendingCategory {
  GENERAL = 'GENERAL',
  TRAVEL = 'TRAVEL',
  DINING = 'DINING',
  GROCERIES = 'GROCERIES',
  GAS = 'GAS',
  BUSINESS = 'BUSINESS',
}

export enum CardTransactionType {
  AUTHORIZATION = 'AUTHORIZATION',
  CAPTURE = 'CAPTURE',
  COMPLETION = 'COMPLETION',
  REFUND = 'REFUND',
  REVERSAL = 'REVERSAL',
  CHARGEBACK = 'CHARGEBACK',
  ATM_WITHDRAWAL = 'ATM_WITHDRAWAL',
  POS_PURCHASE = 'POS_PURCHASE',
  ONLINE_PURCHASE = 'ONLINE_PURCHASE',
  CONTACTLESS = 'CONTACTLESS',
  RECURRING_PAYMENT = 'RECURRING_PAYMENT',
}

export enum CardTransactionStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  COMPLETED = 'COMPLETED',
  DECLINED = 'DECLINED',
  REVERSED = 'REVERSED',
  REFUNDED = 'REFUNDED',
  CHARGEDBACK = 'CHARGEDBACK',
  CANCELLED = 'CANCELLED',
}

export enum CardDeclineReason {
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  CARD_FROZEN = 'CARD_FROZEN',
  EXCEEDS_LIMIT = 'EXCEEDS_LIMIT',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  INVALID_PIN = 'INVALID_PIN',
  EXPIRED_CARD = 'EXPIRED_CARD',
  INVALID_CVV = 'INVALID_CVV',
  BLOCKED_MERCHANT = 'BLOCKED_MERCHANT',
  NETWORK_ERROR = 'NETWORK_ERROR',
  OTHER = 'OTHER',
}

export enum CardEventType {
  CARD_ISSUED = 'card.issued',
  CARD_ACTIVATED = 'card.activated',
  CARD_FROZEN = 'card.frozen',
  CARD_UNFROZEN = 'card.unfrozen',
  CARD_LOCKED = 'card.locked',
  CARD_UNLOCKED = 'card.unlocked',
  CARD_CANCELLED = 'card.cancelled',
  CARD_REISSUED = 'card.reissued',
  CARD_AUTHORIZATION = 'card.authorization',
  CARD_CAPTURED = 'card.captured',
  CARD_COMPLETED = 'card.completed',
  CARD_REFUNDED = 'card.refunded',
  CARD_REVERSED = 'card.reversed',
  CARD_CHARGEBACK = 'card.chargeback',
}
